version: "3.8"

services:
  backend:
    build:
      context: ./research-backend
    container_name: research-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./research-frontend
    container_name: research-frontend
    ports:
      - "80:80"
    depends_on:
      - backend